
services:
  server:
    build: ./server
    container_name: my-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 8080
    env_file:
      - .env

  client:
    build: ./client
    container_name: my-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env

  mongo:
    image: mongo:6
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
